### ISSUE TITLE
First steps

### ISSUE THREAD

**Issue by fnetX** [lydiandy/vsql#1]
Hey there, 

I'm new to V and I'm looking for a way to access sqlite. This isn't usable with your tool yet, is it?

What I'm actually missing in this repository is an overview on how to use this repo and more important: on how to contribute to get this mature soon. 

Do you mind adding some notes on that? I'm somehow lost. Thanks a lot.

**Comment by lydiandy** [comment]
Sorry for the delay. 
The repo just supports pg by now and it is in WIP.
